Repository ucsb-cs156-f24/proj-courses-f24-04, pull requests merged in 2024-11, with the labels that each got.

#31 nk - User friendly error message from 2 sections of same course (UPDATED)
  frontend/src/main/components/Sections/SectionsTable.js
  frontend/src/tests/components/Sections/SectionsTable.test.js
  src/main/java/edu/ucsb/cs156/courses/controllers/PSCourseController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/PSCourseControllerTests.java
Labels: 10

#29 Description optional on personal schedule - UPDATED
  frontend/src/main/components/PersonalSchedules/PersonalScheduleForm.js
  frontend/src/tests/components/PersonalSchedules/PersonalScheduleForm.test.js
Labels: 5, Merge Candidate-CI

#20 PJ - getActiveQuarterList
  src/main/java/edu/ucsb/cs156/courses/controllers/UCSBAPIQuarterController.java
  src/main/java/edu/ucsb/cs156/courses/services/UCSBAPIQuarterService.java
  src/test/java/edu/ucsb/cs156/courses/controllers/UCSBAPIQuarterControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/services/UCSBAPIQuarterServiceTests.java
Labels: 10, Merge Candidate-CI

#32 nk Updates Page only accessible to Admins
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/Admin/AdminUpdatesPage.js
  frontend/src/tests/pages/AdminUpdatesPage.test.js
Labels: 5, Merge Candidate-CI

#34 Created UpdateTable component for updates
  frontend/src/fixtures/updatesFixtures.js
  frontend/src/main/components/Updates/UpdatesTable.js
  frontend/src/stories/components/Updates/UpdatesTable.stories.js
  frontend/src/tests/components/Updates/UpdatesTable.test.js
Labels: 10

#37 Test Added to Fix Stryker Exception on Arrow Function
  frontend/src/main/components/Sections/SectionsOverTimeTable.js
  frontend/src/tests/components/Sections/SectionsOverTimeTable.test.js
Labels: 10, Ready-For-Staff, Merge Candidate-CI

#41 Finals info backend
  src/main/java/edu/ucsb/cs156/courses/controllers/UCSBCurriculumController.java
  src/main/java/edu/ucsb/cs156/courses/entities/FinalExamEntity.java
  src/main/java/edu/ucsb/cs156/courses/models/FinalExam.java
  src/main/java/edu/ucsb/cs156/courses/repositories/FinalExamRepository.java
  src/main/java/edu/ucsb/cs156/courses/services/UCSBCurriculumService.java
  src/test/java/edu/ucsb/cs156/courses/controllers/UCSBCurriculumControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/services/UCSBCurriculumServiceTests.java
Labels: 10, Merge Candidate-CI

#49 UPDATED DropdownSelector Component that allows the user to select a subject area
  frontend/src/main/components/Subjects/SubjectAreaDropdown.js
  frontend/src/stories/components/Subjects/SubjectAreaDropdown.stories.js
  frontend/src/tests/components/Subjects/SubjectAreaDropdown.test.js
Labels: 10, Ready-For-Staff, Merge Candidate-CI

#47 Alvin - GET Endpoint - by job id
  src/main/java/edu/ucsb/cs156/courses/controllers/JobsController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/JobsControllerTests.java
Labels: 10, Merge Candidate-CI

#51 the purge logs button correctly calls the delete all endpoint and deletes all jobs
  frontend/src/main/pages/Admin/AdminJobsPage.js
  frontend/src/tests/pages/AdminJobsPage.test.js
  pom.xml
Labels: FIXME-Address-CR
